### ISSUE TITLE
Is the breaking change of `DateTimeOffset` from `datetime` to `varchar(50)` necessary?

### ISSUE THREAD

**Issue by lauxjpn** [CirrusRedOrg/EntityFrameworkCore.Jet#150]
Commit a6d9058c recently changed the default translation of `DateTimeOffset` from `datetime` to `varchar(50)`.

@ChrisJollyAU Is there an important reason for that? Because this is a serious breaking-change at this point and it should already be possible to just use the EF Core supplied [DateTimeOffsetToStringConverter](https://learn.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.storage.valueconversion.datetimeoffsettostringconverter) value converter, if the default implementation (which is fast and cheap in space) is not enough.

The default `DateTime` implementation that other providers use in cases where the underlying database does not natively support date/time values with time zones, is to just store the UTC value (unless this has recently changed).
If this is currently not done by us, I propose to use that default implementation instead (though we might want to add an option to stay on the existing behavior or at least provide a value converter for existing code).

This also ensures that the default date/time database functions work.

---

Independent of that, if a huge breaking change like this one is introduced, it should always be done using a PR and marked with the `breaking-change` label, so it is documented as such.

The current state breaks existing functionality because the `Add` methods are not being translated anymore. This likely breaks people who are using the daily builds. The `master` branch should be kept as production ready as possible at all times. So changes like this one should only be pushed to `master`, if they are considered working.

**Comment by ChrisJollyAU** [comment]
The change was made so that you could round-trip the DateTimeOffset without losing any data. With saving it as just a datetime you are losing some data. The queries to get the individual components of the data weren't fully working anyway e.g the day or hour would not be the same as what was read from the database.

Using string is actually the same strategy as Sqlite. They only write it to a string and don't support and member or method translations

I do have in my todo list to add an option to configure how to save the DateTimeOffset: string, DateTime (Now), DateTime (UTC)

Can easily use the correct data in the ConfigurePArameter for the DateTimeTypeMapping
