### ISSUE TITLE
Nuget pipeline is not picking up the tag

### ISSUE THREAD

**Issue by ChrisJollyAU** [CirrusRedOrg/EntityFrameworkCore.Jet#185]
@lauxjpn 

Can you check the nuget push pipeline. Trying to push alpha 2 out and have it tagged so it should pick that up to set the officalbuild value to true.

This is the first nuget release since switching from AZDO to Github Actions so something may have changed somewhere

**Comment by ChrisJollyAU** [comment]
Quick update. The checkout action did not checkout any tags by default. 
That is now updated to fetch tags.

Still have an error with the nuget pack section
`/home/runner/work/EntityFrameworkCore.Jet/EntityFrameworkCore.Jet/Version.props(50,9): error : The 'OfficialVersion' property needs to be identical to the 'VersionPrefix' property or to a combination of the 'VersionPrefix' and the 'VersionSuffix' properties.`

**Comment by 0xced** [comment]
It looks like the package [was not published on NuGet](https://github.com/CirrusRedOrg/EntityFrameworkCore.Jet/actions/runs/7171434774/job/19527306712#step:5:90) because this returned `False`:
```
$officialBuild = 'refs/tags/v8.0.0-alpha.2' -match '(?<=^v)\d+\.\d+\.\d+.*$'
```

Could it be that the regex is wrong and should be `(?<=v)\d+\.\d+\.\d+.*$` instead, i.e. without the `^`?

**Comment by ChrisJollyAU** [comment]
@0xced Release pipeline is now all fixed so alpha 2 is on nuget
