### ISSUE TITLE
Dose this support Linux or MacOs apple Silicone

### ISSUE THREAD

**Issue by ImAbhishekTomar** [CirrusRedOrg/EntityFrameworkCore.Jet#217]
I am trying to connect the Microsoft Access Database with the dotenet core app.

**Comment by ChrisJollyAU** [comment]
Short answer:
No. EFCore.Jet only supports Windows and will not work on Linux or Mac

Long Answer:
Microsoft Access database (both .mdb and .accdb) are proprietary file formats developed and maintained by Microsoft. Notably, the requirement is to have the Access Database Engine installed which provides the necessary drivers.
These include:
- OLE DB
- ODBC
- DAO
- ADOX

DAO and ADOX are used for creating the database and getting the tables/columns etc when scaffolding. These are Win32 COM objects and have no equivalent on any unix based system.
OLE DB and ODBC are used with executing SQL queries. There is nothing in unix for OLE DB. There is a unixODBC but there is no official ODBC driver outside of the Microsoft one for Windows

As such given the dependence on Windows only API's (it is what is available from Microsoft), it does not support any Linux or MacOS systems and the chances of it being implemented are rather low

**Comment by PedroGGaspar** [comment]
Interesting, I didn't imagine you would use old COM components like ADOX and DAO in this project, I thought you would only use .NET technologies, like ADO.NET, through OleDB and ODBC.

Does this mean that when deploying a project using EFCore.Jet, we have to install ADOX and DAO files? Or, since it's only used for scaffolding, does it only need to be present on the developer's machine?

By the way, taking advantage of this question, if I intend to use EFCore.Jet only with OleDB, should I install the EntityFrameworkCore.Jet.OleDb NuGet package in my project? Because the project works with or without it.
